### PR TITLE
v0.1.1.7 release prep

### PR DESCRIPTION
**Pull request by emilypi**
@23Skidoo @hvr there wasn't much to do to prep other than removing a WIP. 

Are there any other action items here?

### CODE REVIEW

**Comment by 23Skidoo** [comment]
I think it's ready to go.

**Comment by emilypi** [comment]
Thank for getting back so quickly @23Skidoo!  The candidate can be viewed here: https://hackage.haskell.org/package/base16-bytestring-0.1.1.7/candidate

**Comment by 23Skidoo** [comment]
@emilypi Looks good to me. You may want to add your name to README#Authors, since me and @hvr are mentioned there.

**Comment by emilypi** [comment]
Ah good catch - will do

**Comment by emilypi** [comment]
On green, I'll merge and release

**Pull request merged**
